// import "./globals.css";
import ThemeRegistry from "@/lib/theme/ThemeRegistry";
import { ApolloWrapper } from "@/lib/apollo/Provider";
import { Container } from "@mui/material";
import Bar from "@/components/Navigation/Bar";
import Auth from "@/lib/contexts/Authentication";
import { cookies } from "next/headers";
import { getClient } from "@/lib/apollo/client";
import { gql } from "@apollo/client";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ME = gql`
  query Me {
    me {
      id
      username
      email
      confirmed
    }
  }
`;

async function getUserData() {
  const token = cookies().get("token");
  console.log(token);

  if (token?.value) {
    const { data } = await getClient().query({
      query: ME,
      context: { headers: { authorization: `Bearer ${token.value}` } },
    });

    return data.me;
  }
}

export default async function RootLayout({ children }) {
  // const me = await getUserData();

  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <ThemeRegistry options={{ key: "mui" }}>
            <Auth>
              <Bar />
              <Container component="main">{children}</Container>
            </Auth>
          </ThemeRegistry>
        </ApolloWrapper>
      </body>
    </html>
  );
}
